apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opereto-worker-node
spec:
  serviceName: opereto-worker
  replicas: 3
  selector:
    matchLabels:
      app: opereto-worker-cluster
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opereto-worker-cluster
    spec:
      terminationGracePeriodSeconds: 300
      containers:
      - image: opereto/worker
        name: opereto-worker
        resources:
          requests:
            memory: 16Gi
          limits:
            memory: 16Gi
        env:
        - name: agent_name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: opereto_host
          value: <OPERETO_HOST>
        - name: opereto_user
          valueFrom:
            secretKeyRef:
              name: worker-config
              key: OPERETO_USERNAME
        - name: opereto_password
          valueFrom:
            secretKeyRef:
              name: worker-config
              key: OPERETO_PASSWORD
        - name: javaParams
          value: "-Xms4000m -Xmx4000m"
        - name: log_level
          value: "info"
        volumeMounts:
        - name: data
          mountPath: /var/data


  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      storageClassName: worker-ssd
      resources:
        requests:
          storage: 100Gi
